# SITE CONFIGURATION
baseurl: ""
url: "https://ghedamat.github.io"

# THEME-SPECIFIC CONFIGURATION
title: Mattia Gheda
description: "Thoughts on Software, NixOS, Elixir and self discovery"      # used by search engines
#avatar: assets/img/triangle.png                         # Empty for no avatar in navbar
favicon: assets/favicon.ico                             # Icon displayed in the tab

# Header and footer text
header_text: Ghedamat
header_feature_image: https://gsnaps.s3-us-west-2.amazonaws.com/monkey.png
footer_text: "Ghedamat's blog"

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for social icons, share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
disqus_shortname:                                       # Your discus shortname for comments
cusdis_app_id:                                          # Your cusdis data-app-id
color_theme: light                                       # auto, dark or light

# PAGINATION
paginate: 10
paginate_path: "/blog/page:num"

permalink: /:year-:month-:day/:title
# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed, jekyll-redirect-from]
exclude: [".jekyll-cache", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
#remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
remote_theme: mmistakes/so-simple-theme@3.2.0